version: '3.1'
services:
  common-storage:
    ports:
    - "8080:8080"
    build:
      context: .
      args:
      - CS_TITLE=${CS_TITLE}
      - CS_USER=${CS_USER}
      - CS_DESCRIPTION=${CS_DESCRIPTION}
      - CS_PASSWORD=${CS_PASSWORD}
      - CS_PORT=${CS_PORT}
      - CS_SQLITE_DB_PATH=${CS_SQLITE_DB_PATH}
      - CS_DB_ENGINE=${CS_DB_ENGINE}
      - CS_LOGGER=${CS_LOGGER}

    environment:
      - CS_TITLE=${CS_TITLE}
      - CS_USER=${CS_USER}
      - CS_DESCRIPTION=${CS_DESCRIPTION}
      - CS_PASSWORD=${CS_PASSWORD}
      - CS_PORT=${CS_PORT}
      - CS_SQLITE_DB_PATH=${CS_SQLITE_DB_PATH}
      - CS_DB_ENGINE=${CS_DB_ENGINE}
      - CS_LOGGER=${CS_LOGGER}
    volumes:
      - './database:/database'
