version: '3.1'
services:
 # env mapings: https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers
  common-storage:
    ports:
    - "8080:8080"
    build:
      context: .
      args:
      - CS_USER=${CS_USER:-user}
      - CS_PASSWORD=${CS_PASSWORD:-changeme}
      - CS_TITLE=${CS_TITLE}
      - CS_DESCRIPTION=${CS_DESCRIPTION}
      - CS_SQL_DB_PATH=${CS_SQL_DB_PATH:-./common-storage.sqlite}
      - CS_PORT=${CS_PORT:-8080}
    environment:
    - CS_USER=${CS_USER:-user}
    - CS_PASSWORD=${CS_PASSWORD:-changeme}
    - CS_TITLE=${CS_TITLE}
    - CS_DESCRIPTION=${CS_DESCRIPTION}
    - CS_SQL_DB_PATH=${CS_SQL_DB_PATH:-./common-storage.sqlite}
    - CS_PORT=${CS_PORT:-8080}