# fly.toml app configuration file generated for common-storage-small-forest-273 on 2024-03-19T20:05:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'common-storage'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="kv_store"
  destination="/app/database"

[[services]]
  port = 443
  handlers = ["tls", "http"]
  force_https = true
  internal_port = 80
  protocol = "tcp"

[[vm]]
  size = 'shared-cpu-1x'
