name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        deno-version: [1.25.0]

    runs-on: ${{ matrix.os }}
    steps:
    - run: bash ./bs/test.sh
